### ISSUE TITLE
[Request] iPX - Upper edge of ifnormation hidden by notch

### ISSUE THREAD

**Issue by 0xhckr** [Shade-Zepheri/Nougat#2]
When you swipe down, a lot of information is hidden by the notch)

(Btw I tried compiling this project to no avail. I'm missing SDKs it seems? I wanted to make a PR with the required changes but I don't even know which SDK to go track down)

**Comment by Shade-Zepheri** [comment]
Use the 11.2 SDK from https://github.com/theos/sdks
