### ISSUE TITLE
Compiling / New beta?

### ISSUE THREAD

**Issue by nayu-codes** [Shade-Zepheri/Nougat#8]
Hi! Is it possible to push a new beta on your repo (seeing there's some support for notifications now)? I tried compiling it on my own, but theos just kept throwing me the
```ld: framework not found NougatServices```
error.

**Comment by nayu-codes** [comment]
With the new updates, I'm currently getting

`duplicate symbol '_UIWindowLevelTextEffects'`
`duplicate symbol '_UIWindowLevelNotificationCenter`
`duplicate symbol '_UIWindowLevelStatusBarLockScreen'`
`duplicate symbol '_UIWindowLevelAlertReal'`

for `NUABrightnessModuleController.m` and `NUANotificationShadeController.x`

**Comment by Shade-Zepheri** [comment]
Thats an issue on theos' end. There might be other errors due to the way my old work flow was setup, I'll get around to fixing those eventually.

**Comment by nayu-codes** [comment]
Managed to finally built it but seems like it still doesn't work on iOS 13 (the NC remains unchanged) feelsbad :/

Still really looking forward to it though :p
